on:
  release:
    types: [published]

jobs:
  release-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: send-discord-webhook
        id: discord
        uses: NatroTeam/discord-release-action@v1.2
        with:
          webhook_url: ${{secrets.RELEASE_WEBHOOK_URL}}
